---
- hosts: localhost
  become: true
  tasks:
    - name: stop if we have old docker container
      command: docker stop devops-container
      ignore_errors: yes

    - name: remove stopped docker container
      command: docker rm devops-container
      ignore_errors: yes

    - name: pull docker image from dockerhub
      command: docker pull divyabharathwaj/abctechapp:latest

    - name: creating docker image
      command: docker run -d --name devops-container -p 8010:8080 divyabharathwaj/abctechapp
